namespace CloneDash.Compatibility.MuseDash
{
	public static partial class MuseDashCompatibility
    {
		/// <summary>
		/// Muse Dash's IBMS codes, which defines behavior of certain entities
		/// </summary>
		public enum IBMSCode
        {
            None,
            SmallNormal,
            SmallUp,
            SmallDown,
            Medium1Normal,
            Medium1Up,
            Medium1Down,
            Medium2Normal,
            Medium2Up,
            Medium2Down,
            Large1,
            Large2,
            Raider,
            Hammer,
            Gemini,
            LongPress,
            Mul,
            Block,
            RaiderFlip,
            HammerFlip,
            DoubleSpeed1 = 24,
            DoubleSpeed2,
            DoubleSpeed3,
            RoadSpeed1,
            RoadSpeed2,
            RoadSpeed3,
            AirSpeed1,
            AirSpeed2,
            AirSpeed3,
            BossNear1 = 37,
            BossNear2,
            BossAttack1,
            BossAttack2_1,
            BossAttack2_2,
            BossMul1,
            BossMul2,
            BossBlock,
            BossIn = 46,
            BossOut,
            BossFar1Start,
            BossFar1End,
            BossFar2Start,
            BossFar2End,
            BossFar1To2,
            BossFar2To1,
            NoteHide = 55,
            NoteShow,
            BossHide,
            BossShow,
            ToggleScene1 = 60,
            ToggleScene2,
            ToggleScene3,
            ToggleScene4,
            ToggleScene5,
            ToggleScene6,
            ToggleScene7,
            ToggleScene8,
            ToggleScene9,
            ToggleScene10,
            TouhouRedPoint = 72,
            Ghost,
            Hp,
            Music,
            SceneHide = 77,
            SceneShow,
            CanvasUpScroll,
            CanvasDownScroll,
            CanvasScrollOver,
            RandomWave,
            RandomWaveOver,
            RgbSplit,
            RgbSplitOver,
            ShadowEdgeIn,
            ShadowEdgeOut,
            OldTv,
            OldTvOver,
            FlashStart,
            FlashHigh,
            FlashEnd,
            NoteFreeze,
            NoteUnfreeze,
            BgFreeze,
            BgUnfreeze,
            PixelStart,
            PixelEnd,
            GrayScaleStart,
            GrayScaleEnd,
            OpenAuto = 106,
            CloseAuto,
            TouhouLightNormal,
            TouhouLightUp,
            TouhouLightDown,
            TouhouLightCross,
            TouhouStarNormal,
            TouhouStarUp,
            TouhouStarDown,
            TouhouStarCross,
            TouhouBigNormal,
            TouhouBigUp,
            TouhouBigDown,
            TouhouBigCross,
            TouhouScalyNormal,
            TouhouScalyCross,
            TouhouKnifeNormal,
            TouhouKnifeCross,
            TouhouDivideDanmaku1,
            TouhouDivideDanmaku2,
            TouhouDivideDanmaku3
        }
    }
}
