<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CloneDash.MuseDash1Compatibility\CloneDash.MuseDash1Compatibility.csproj" />
	</ItemGroup>
	
	<Import Project="..\ApplyNucleusAssemblyAttribute.targets" />
	
	<ItemGroup>
		<Compile Include="..\GlobalUsings.cs" Link="Usings\Globals\GlobalUsings.cs" />
	</ItemGroup>
	
	<ItemGroup>
	  <PackageReference Include="FFMediaToolkit" Version="4.8.1" />
	  <PackageReference Include="SharpCompress" Version="0.50.4" />
	</ItemGroup>
</Project>
