using Newtonsoft.Json;
using Nucleus.Common.FileSystem;
using Nucleus.Util;

using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text;

namespace Nucleus.Files;

public class FileSystem : IFileSystem
{
	public Dictionary<UtlSymId_t, SearchPathID> Path { get; } = [];
	private bool initialized = false;

	/// <summary>
	/// This stores some images in-code for the UI
	/// todo; a MUCH better way to do this, ie. something encoding in the application itself. I just haven't done much of that before
	/// </summary>
	/// <returns></returns>
	static MemorySearchPath MemBackedImages() {
		var mempath = new MemorySearchPath();

		using (var up32 = mempath.Open("ui/up32.png", FileAccess.Write, FileMode.Create))
			up32!.Write(Convert.FromBase64String("iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAANmVYSWZNTQAqAAAAGAAAAEgAAAABAAAASAAAAAEAAgEaAAUAAAABAAAACAEbAAUAAAABAAAAEAAAAACQeO+8AAAACW9GRnMAAAAAAAAAAADaKrbOAAAACXBIWXMAAAsSAAALEgHS3X78AAAAHXRFWHRjeWNsZXMuVmlldyBMYXllci5zYW1wbGVzADI1Nlh8UgYAAAAldEVYdGN5Y2xlcy5WaWV3IExheWVyLnRvdGFsX3RpbWUAMDA6MDAuODaDnET6AAAAJnRFWHRjeWNsZXMuVmlldyBMYXllci5yZW5kZXJfdGltZQAwMDowMC4xM5u9/ecAAAAvdEVYdGN5Y2xlcy5WaWV3IExheWVyLnN5bmNocm9uaXphdGlvbl90aW1lADAwOjAwLjcy2y0CQwAAECtJREFUWAkBIBDf7wEBAQEAAAAAAP///wABAQEAAQEBAP///wD///8AAQEBAAAAAAD///8AAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAP///wACAgIA////AAAAAAAAAAAAAAAAAAEBAQD///8AAAAAAAAAAAAAAAAA////AAEBAQAAAAAA////AAEBAQEAAAAAAAAAAAAAAAAA////AAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAP///wAAAAAAAAAAAAAAAAABAQEA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEA////AAAAAAAAAAAAAAAAAAEBAQAAAAAA////AAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAAAAAD///8AAAAAAAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAA////AAAAAAAAAAAAAAAAAAAAAAD+/v4AAQEBAAAAAAABAQEAAAAAAP//AQDa/v4BAgIBAP///wAAAAAA////AAEBAQAAAAAAAQEBAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAABAQEAAAAAAAEBAQEAAAAAAAEBAQAAAAAA////AAAAAAAAAAAAAAAAAAEBAQD///8AAAAAAAAAAAAAAAAAAAAAAPn+/gPxAAAn+gAA/wkAANoTAwL9AP8AAP///wABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQD///8AAAAAAAABAQEAAQEBAAEBAQABAQEAAQEBAAEBAQABAQEAAQEBAAAAAAABAQEAAQEBAAICAgABAQEA////AeT//0nz///c9f//4er//03///8BAQEBAAEBAQABAQEAAQEBAAEBAQABAQEAAQEBAAEBAQABAQEAAQEBAAAAAAABAQEAAQEBAAACAgIAAQEBAAEBAQABAQEAAgICAAAAAAABAQEAAQEBAAEBAQACAgIAAgICAAEBAQACBAEA4P//IvD//8/t///+6////+7//8vp//8eAQUBAAEBAQAAAAAAAQEBAAEBAQABAQEAAQEBAAAAAAABAQEAAQEBAAEBAQABAQEAAQEBAAL///8AAAAAAAAAAAAAAAAA////AAEBAQD///8AAAAAAAAAAAD///8A////AAECAgDn+/4KBgAAcAAAACz/AAABAAAAAAIAADECAAB29/r+CAABAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAA////AAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAP38/AH5AABMBwAAX/8AAAQBAAAAAwAAAP4AAAMHAABb6wAATfn9/gIAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAQEBAAAAAAAAAAAA////AAAAAAAAAAAABQcBAOIAACMOAAB9AgAADv8AAAABAAAAAAAAAAAAAAD8AAAQCwAAeu0AAB8CCAAAAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAEBAQAAAAAAAAAAAAIBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAQEBAAAAAAAAAAAA6Pf9DAwAAHgAAAAq/wAAAAEAAAAAAAAAAAAAAP8AAAD/AAAAAgAALwMAAHjn9v4N////AAAAAAAAAAAAAQEBAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAL///8AAAAAAAAAAAAAAAAAAAAAAAAAAAACAgIAAAAAAAAAAAD5/v4D/AAATgQAAFX+AAACAAAAAAEAAAAAAAAAAAAAAP8AAAAAAAAA/QAAAQoAAFkAAABN/v7+AgAAAAAAAAAA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIFAADnAAAmCQAAe/sAAA4AAAAAAAAAAP4AAAAAAAAA/wAAAAAAAAABAAAAAAAAAPgAAA0HAAB86AAAJAACAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQD///8AAAEBAOr5/gsIAABx+wAAKQIAAAABAAAAAQAAAAIAAAABAAAAAQAAAAEAAAAAAAAAAgAAAP8AAAD+AAAoCQAAd+z8/gz///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v39AfgAAFUEAABY/wAAAQAAAAD/AAAAAAAAAP8AAAD/AAAAAAAAAAAAAAD/AAAA/QAAAAMAAAD+AAABAgAAVvoAAFH5/v4DAAAAAAAAAAD///8AAAAAAAAAAAD///8AAAAAAAECAgIA////AAAAAAAAAAAAAAAAAAAAAADx/v4B9QAAKAkAALH7AAAlAgAAAAMAAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD/AAAAAAAAAAEAAAAAAAAA/QAAAAcAANj6AABVFgYD1P/8/wABAQEA////AAAAAAAAAAAAAAAAAAL///8AAAAAAAAAAAAAAAAAAAAAAAAAAAD7AAALBgAAfAAAACQCAAAAAQAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAgAAAPwAACcAAAB36Pr9DAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAIBAQEAAAAAAAAAAAAAAAAAAAAAAP7+/gL5AABZBAAAT/wAAAECAAAAAgAAAAAAAAAAAAAA/wAAAAAAAAABAAAA/wAAAAEAAAACAAAAAQAAAAEAAAABAAAA/wAAAP4AAAEGAABTAQAAWv7+/gIAAAAAAAAAAAEBAQAAAAAAAAAAAAL///8AAAAAAAAAAAAAAAAAAgQAAOMAACwLAAB0/AAACwEAAAD/AAAA/wAAAP4AAAAAAAAAAAAAAP8AAAD/AAAAAAAAAP4AAAD/AAAA/gAAAP8AAAD/AAAAAgAAAAMAAAD5AAAJBwAAcusAAC0BAwAAAQEBAP///wAAAAAAAQEBAAIAAAAAAAAAAAAAAAAEAwMA4/r+DwYAAH79AAAjAAAAAAEAAAAAAAAA/wAAAP8AAAAAAAAAAQAAAAEAAAAAAAAAAQAAAAIAAAABAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA/gAAJQAAAHvt+/4Qvf39AQAAAAAAAAAA////AAIAAAAAAAAAAAAAAAASERIAAAAASAcAAEoAAAADAQAAAAEAAAACAAAAAgAAAAIAAAAAAAAAAQAAAAEAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAACAAAAAgAAAAEAAAAEAAAAAAAAAgQAAEv5AABKLAAAAQABAAAAAAAAAAAAAAQAAAAAAAAAAAEBAQDo6ukB3wAACQ4AAO76AAAIAAAAAP4AAAAAAAAA/wAA/wEAAAH/AAD/AAAAAQAAAAEAAAD/AQAAAP8AAP8AAAABAQAAAf8AAP8AAAAAAQAAAAEAAAAAAAAA/wAAAAAAAPb3AAAFBQAAAAD/AAAAAAAAAAAAAAEBAQEAAAAAAAAAAAAAAQIA6v38CAAAAB0BAAAJAwAA/v8AAAEAAAAB/wAA/gIAAAEAAAABAgAA/wAAAP//AAABAQAAAP8AAAEAAAAA/wAA/wEAAAH/AAAAAQAAAAAAAP7/AAAAAAAAAP8AAPkGAADjDQQC+AD+AAAAAAAAAQEBAAEBAQEAAAAAAAAAAAAAAAAA////AAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAAAA/wD//wAAAAAAAAAAAAAAAAAAAQEBAAIAAAAAAQEBAAAAAAAAAAAAAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQAAAAAA////AAEBAQABAQEAAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAAAAQD///8AAAAAAAAAAAAAAAAAAAAAAAEBAQEAAAAAAAAAAAAAAAAA////AAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAQEBAAMBAQEAAAAAAAAAAAAAAAAAAQEBAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCAQEAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAEAAAAAAAAAAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEA////AP///wACAgIA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAICAgAAAAAA////AAAAAAAAAAAAAAAAACNVvPe326yPAAAANmVYSWZNTQAqAAAAGAAAAEgAAAABAAAASAAAAAEAAgEaAAUAAAABAAAACAEbAAUAAAABAAAAEAAAAACQeO+8AAAAAElFTkSuQmCC"));

		using (var left32 = mempath.Open("ui/left32.png", FileAccess.Write, FileMode.Create))
			left32!.Write(Convert.FromBase64String("iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAANmVYSWZNTQAqAAAAGAAAAEgAAAABAAAASAAAAAEAAgEaAAUAAAABAAAACAEbAAUAAAABAAAAEAAAAACQeO+8AAAACW9GRnMAAAAAAAAAAADaKrbOAAAACXBIWXMAAAsSAAALEgHS3X78AAAAHXRFWHRjeWNsZXMuVmlldyBMYXllci5zYW1wbGVzADI1Nlh8UgYAAAAldEVYdGN5Y2xlcy5WaWV3IExheWVyLnRvdGFsX3RpbWUAMDA6MDAuNzN0bqy6AAAAJnRFWHRjeWNsZXMuVmlldyBMYXllci5yZW5kZXJfdGltZQAwMDowMC4xMAK0rF0AAAAvdEVYdGN5Y2xlcy5WaWV3IExheWVyLnN5bmNocm9uaXphdGlvbl90aW1lADAwOjAwLjYztTEDlAAAECtJREFUWAkBIBDf7wEBAQEAAAAAAP///wABAQEAAQEBAP///wD///8AAQEBAAAAAAD///8AAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAP///wACAgIA////AAAAAAAAAAAAAAAAAAEBAQD///8AAAAAAAAAAAAAAAAA////AAEBAQAAAAAA////AAEBAQEAAAAAAAAAAAAAAAAA////AAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAP///wAAAAAAAAAAAAAAAAABAQEA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A////AAAAAAAAAAAAAAAAAAAAAAD///8AAAIBAP7+/gH+/v4BAAADAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAA5/z+EAYAAEf8AAAI/wAAqRYCAvgAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAQEBAAEBAQABAQEAAQEBAAEBAQABAQEAAQEBAAEBAQACAgIAAAAAAAEBAQABAQEAAQEBAAICAgABAQEAAAAAAAEBAQABAQEAAQICAPT//wXn//8w6v//p/D///Tx///i5P//JAEBAQAAAAAAAQEBAAEBAQABAQEAAQEBAAQAAAAAAAAAAAAAAAAAAAAA////AAEBAQAAAAAAAAAAAAAAAAD+/v4AAQEBAAAAAAABAQEA////AP///wAAAAAAAQEBAP///wADAgEA7P39DfYAAFcMAABz/AAAJv0AAAIFAAD5BgAACQAAAAABAQEAAAAAAAAAAAABAQEA////AAQAAAAAAAAAAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAABAQEA////APr//wTtAAAn/QAAeAQAAFD7AAAMAAAAAAEAAAAAAAD+AAAAAAAAAAAAAAAAAAAAAAEBAQD///8AAAAAAAQAAAAAAAAAAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAP7+/gABAQEAAAAAAAEBAQD///8AAAAAAAAAAAD9/f0B+QAACvAAAFcKAAB0/gAAKf4AAAAAAAAAAgAAAP8AAAD+AAABAAAAAAAAAAAAAAAAAAAAAP7+/gABAQEAAAAAAAQBAQEA////AAAAAAAAAAAAAQEBAP7+/gABAQEAAAAAAAEBAQABAQEAAAAAAP///wAAAAAAAAAAAPr+/gPnAAAmBgAAdgUAAFP8AAAMAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAf///wABAQEAAAAAAAEBAQAAAAAAAAAAAAT///8AAAAAAAAAAAAAAAAA////AAEBAQD///8AAQEBAAAAAAD///8AAAAAAAEBAQAA//8A8v7+Ce8AAFAJAAB4/wAAKgEAAAQAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA/wAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAA////AAEBAQABAQEAAAAAAAAAAAAAAAAAAAAAAP39/QLpAAAg9gAAdQUAAFv9AAAMAwAAAf4AAAABAAAAAQAAAAAAAAD/AAAAAAAAAAEAAAABAAD//wAAAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAQEBAAAAAAAAAAAA////AAEBAQD+/v4BAAAACO0AAEwFAAB8AQAAKv8AAAQBAAAAAAAAAAEAAAAAAAAAAAAAAP8AAAAAAAAAAQAAAAAAAAAAAAAABAAAAAAAAAAAAAAA////AAICAgD///8AAAAAAAIBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAQEBAP7+/gHsAAAh6wAAigQAAJsAAAAtAAAABAEAAAABAAAAAAAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAD+AAABAgAA/4r+/gEAAAAAAQEBAP///wAAAAAAAAAAAAT///8AAAAAAAAAAAAAAAAAAAAAAAAAAAACAgIA/f39A+kAAEYHAACF/wAALv4AAAMAAAAAAAAAAAAAAAABAAAAAQAAAP4AAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA+wAAAXYCAv8AAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA6gAAJAgAAJT+AAAh/wAAAQEAAAABAAAAAQAAAP8AAAAAAAAA/wAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAP8AAAACAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQD///8A/QAABP8AAP8AAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAD/AAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAGQAA1/oAAHIBAADNAgAA+wAAAAD+AAAAAAAAAAAAAAD/AAAAAAAAAAEAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAD/AAAAAQAAAAD///8AAAAAAAAAAAD///8AAAAAAAIBAQEAAAAAAAAAAAAAAAAAAAAAAP///wAAAAAAAQEB/gMAALUCAABX+QAAmwMAAPACAAAA/wAAAP8AAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAD/AQAA/wAAAAACAgIAAAAAAAAAAAABAQEAAAAAAAL///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBABUCAv0RBgLeDwAAdvcAAGcBAADPAwAA/gAAAAAAAAAA/wAAAP8AAAAAAAAAAgAAAAEAAAAAAAAAAAAAAP8AAAAAAAAB/wAA/wAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAIBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//AAACwMD9RcAAKwAAABY+QAAmwIAAPMCAAD+AAAAAAAAAAAAAAAAAQAAAAEAAAABAAAA/wAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAEBAQAAAAAAAAAAAAL///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAICAv4TBgLaDwAAc/cAAGb/AADUAQAA/f8AAAD/AAAA/gAAAP8AAAD/AAAAAAAAAAEAAAD/AAAAAAAAAab+/gEAAAAAAQEBAP///wAAAAAAAQEBAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAD//QEACAME9QoAAKsDAABX+QAAowUAAPYBAAD+AAAAAAIAAAAAAAAAAQAAAAAAAAACAAD//AAAAFoCAv8AAAAA////AAAAAAAAAAAA////AAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAQD/ABACAv0SCQPYCwAAbvUAAGoCAADbAgAA//0AAAAAAAAAAAAAAAAAAAD/AAAA/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAEBAQAAAAAAAAAAAAAAAAAAAAAA////AAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAAAAAD9+f8ADgMC8xgAAKL7AABV/AAApAYAAPUBAAAAAAAAAP4AAAABAAAB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAP///wAAAAAAAAAAAAAAAAABAQEAAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAAAAAAAAAAAAAP8AAAICAv8XBwPTCQAAavMAAG0DAADYAQAA//8AAAD/AAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAAIAAAAAAAAAAAAAAAAAAAAA////AAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAAAAAAAAAAAAQEBAAAAAAD++/8ADAQE9AcAAKPzAABY9wAArQYAAPYBAAD3AwAA9wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQD///8AAAAAAAEBAQAAAAAAAAAAAP///wACBwAA8/f+EPMAAEf+AAAHAQAArBoDA/b+/v4AAQEBAAAAAAAAAAAAAQEBAAEBAQEAAAAAAAAAAAAAAAAA////AAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPb+/gEIAAAAAwMD/////wAAAAAAAAAAAAAAAAAAAAAAAQEBAAEBAQEAAAAAAAAAAAAAAAAAAAAAAAEBAQD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMBAQEAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAEAAAAAAAAAAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEA////AP///wACAgIA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAICAgAAAAAA////AAAAAAAAAAAAAAAAAAoI6E5Q+oYlAAAANmVYSWZNTQAqAAAAGAAAAEgAAAABAAAASAAAAAEAAgEaAAUAAAABAAAACAEbAAUAAAABAAAAEAAAAACQeO+8AAAAAElFTkSuQmCC"));

		using (var right32 = mempath.Open("ui/right32.png", FileAccess.Write, FileMode.Create))
			right32!.Write(Convert.FromBase64String("iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAANmVYSWZNTQAqAAAAGAAAAEgAAAABAAAASAAAAAEAAgEaAAUAAAABAAAACAEbAAUAAAABAAAAEAAAAACQeO+8AAAACW9GRnMAAAAAAAAAAADaKrbOAAAACXBIWXMAAAsSAAALEgHS3X78AAAAHXRFWHRjeWNsZXMuVmlldyBMYXllci5zYW1wbGVzADI1Nlh8UgYAAAAldEVYdGN5Y2xlcy5WaWV3IExheWVyLnRvdGFsX3RpbWUAMDA6MDAuNzWdDQmPAAAAJnRFWHRjeWNsZXMuVmlldyBMYXllci5yZW5kZXJfdGltZQAwMDowMC4wOBV0FS4AAAAvdEVYdGN5Y2xlcy5WaWV3IExheWVyLnN5bmNocm9uaXphdGlvbl90aW1lADAwOjAwLjY3slzHjQAAECtJREFUWAkBIBDf7wEBAQEAAAAAAP///wABAQEAAQEBAP///wD///8AAQEBAAAAAAD///8AAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAP///wACAgIA////AAAAAAAAAAAAAAAAAAEBAQD///8AAAAAAAAAAAAAAAAA////AAEBAQAAAAAA////AAEBAQEAAAAAAAAAAAAAAAAA////AAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAP///wAAAAAAAAAAAAAAAAABAQEA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwQA0v7+AQYDBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A////AAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAEBAQEAAAAAAAAAAAAAAAAAAAAAAAABAQDy/f0H7AAAWvgAAPcgAAC1FQoD8/X4/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAQEBAAEBAQABAQEAAQEBAAQJAQDk//8k8f//4+n///Xr//+p5///MP///wMBAQEAAQEBAAICAgABAQEAAAAAAAEBAQABAQEAAQEBAAEBAQABAQEAAAAAAAEBAQAAAAAAAQEBAAEBAQAAAAAAAQEBAAEBAQABAQEAAQEBAAIAAAAAAAAAAAAAAAAAAAAA////AAEBAQD5AAAK+wAACQIAAAoBAABUBwAAqesAAGPt/v4N/v7+Af//AAAAAAAAAQEBAP///wAAAAAA////AAEBAQAAAAAAAQEBAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAABAQEAAAAAAAIAAAAAAAAAAAEBAQABAQEAAQEBAP38/wAGAAD/BQAAAQQAAAADAAAC/gAAJQUAAI7+AACa5AAALP7+/QMBAQEAAAAAAAEBAQAAAAAAAQEBAP7+/gAAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAEBAQD///8AAAAAAAIAAAAAAAAAAP///wD///8AAAAAAP/+AAD/AAABAwAA//8AAAAAAAAA/wAAAf0AAAsBAABXBgAAquwAAFvr/f0LBAMAAAAAAAAAAAAAAAAAAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7+/gAAAAAAAAAAAAIBAQEAAAAAAAAAAAAAAAAAAQEBAP///wABAAABAAAAAP8AAAABAAAABAAAAAIAAAAAAAABAgAAKAMAAJX8AACU3fv+KP3+/gIAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAEBAQAAAAAAAAAAAAL///8AAAAAAAAAAAAAAAAA////AAH/AQAFAAD//gAAAfwAAAD/AAAAAQAAAAIAAAABAAAAAwAAAP8AAAwGAABfDAAAq+0AAFnm/v4MBQUAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAA////AAD/AAABAAD/AAAA//8AAAD/AAAA/wAAAP4AAAAAAAAAAgAAAAEAAAD+AAAB/gAALAcAAJgCAACQ3Pn+JO/+/gIAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAQEBAAABAAD/AAAA/gAAAP4AAAAAAAAAAQAAAAEAAAACAAAA/wAAAAAAAAABAAAAAQAAAPsAAAwGAABhEAAArvkAAFHu/v4IAQMBAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAEBAQAAAAAAAAAAAAIBAQEAAAAAAAAAAAAAAAAAAAAAAAD/AAD9AAABAQAAAAAAAAABAAAA/wAAAAAAAAAAAAAA/wAAAAAAAAABAAAAAgAAAAAAAAD+AAAC+wAALQkAAJv6AACL4fv9IQgLBgAAAAAAAQEBAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAL///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAD+AAAA/wEAAAAAAAAAAAAAAAAAAAD/AAAAAAAAAAAAAAD9AAAA/wAAAAEAAAAAAAAAAQAAAPwAABEHAABpDwAAq+Pz+Ezs/v4E////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAgAAAQEAAAABAAAAAQAAAP8AAAD/AAAAAQAAAAAAAAABAAAA/wAAAP8AAAACAAAAAAAAAAAAAAD/AAAD+gAAMwUAAJT2AAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQAAAAD/AAAAAP8AAAAAAAAA/wAAAAEAAAAAAAAAAAAAAAEAAAABAAAA/wAAAAAAAAD/AAAAAAAAAAAAAAD9AAAAAAAA//4AAPwDAAACAAEAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAACAQAA/wEAAAD/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA/wAAAP0AAAAFAAD9CAAAyfoAAHEKAADaAP8AAAAAAAD///8AAAAAAAAAAAD///8AAAAAAAQBAQEA////AAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAQEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAAIAAAD/AAAA/gAAAAoAAPDyAACkBwAAjxYAAN8CAgL/AQEBAP///wACAgIA////AAAAAAABAQEAAAAAAAT///8AAAAAAAAAAAAAAAAAAAAAAAABAAACAAD+AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAAAAAAAAAAAAAQAAAP4AAAD/AAD9CAAA1+4AAIQWAACy8gAA+AMCAv8AAAAA////AAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAQBAQEA////AAAAAAAAAAAAAAAAAAD/AAD9AAAC/wAAAAEAAAAAAAAAAgAAAAAAAAAAAAAA/wAAAAEAAAD+AAAA+wAAAAsAAPPzAACnAgAAiBwAAOADAgP//v/+AAEBAQAAAAAAAQEBAP///wAAAAAAAAAAAAEBAQD///8AAAAAAAT///8AAAAAAAAAAAAAAAAAAAAAAAAAAAACAAD/AAAAAAAAAAABAAAAAAAAAP4AAAAAAAAAAQAAAPwAAAD/AAD9BAAA2PYAAIcKAACwEwMC9f7/AAAAAAAAAQEBAAEBAQD///8A////AAAAAAAAAAAAAQEBAP///wAAAAAAAQEBAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD9AAD/AAAAAf8AAAD/AAAA/wAAAAAAAAD/AAAA/AAAAAUAAPP6AACqAQAAjhYAANcCAgL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAAAAAAAAAAA////AAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAD9AAAB/wAA//4AAAD/AAAAAAAAAP0AAAD6AAD/CQAA2P4AAIwOAACoDwYC9vv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAAAAAA////AAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAEBAQD///8AAAAAAAABAAACAAAA/gAAAAMAAAABAAAA+wAAAAQAAPUCAACz/wAAgRIAANoCAgP+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAP///wAAAAAAAAAAAAD/AAD+AAABAAAAAAQAAAD+AAD+AQAA3P0AAIwPAACoEwgE8/j6/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAQEBAAAAAAABAQEAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAQEBAAQAAAAAAAAAAAAAAAAAAAAA////AAEAAQD3AAD4DQAA9wYAAPP4AAC6CAAAhAwAANQCAwP8AP//AAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEAAQEBAP///wAAAAAAAAAAAAAAAQDs/v0J+gAAVwQAAPYPAAC4BQAA8wICAv8AAAAAAAAAAAEBAQD///8AAAAAAAEBAQAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQD+/v4AAQEBAAAAAAAAAAAAAQEBAAEBAQEAAAAAAAAAAAAAAAAA////AAEBAQAABgIA/vj8ARETE//x7+8AAAAAAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAQEBAAEBAQEAAAAAAAAAAAAAAAAAAAAAAAEBAQD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMBAQEAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAEAAAAAAAAAAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEA////AP///wACAgIA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAICAgAAAAAA////AAAAAAAAAAAAAAAAAF0/CenUe45dAAAANmVYSWZNTQAqAAAAGAAAAEgAAAABAAAASAAAAAEAAgEaAAUAAAABAAAACAEbAAUAAAABAAAAEAAAAACQeO+8AAAAAElFTkSuQmCC"));

		using (var down32 = mempath.Open("ui/down32.png", FileAccess.Write, FileMode.Create))
			down32!.Write(Convert.FromBase64String("iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAANmVYSWZNTQAqAAAAGAAAAEgAAAABAAAASAAAAAEAAgEaAAUAAAABAAAACAEbAAUAAAABAAAAEAAAAACQeO+8AAAACW9GRnMAAAAAAAAAAADaKrbOAAAACXBIWXMAAAsSAAALEgHS3X78AAAAHXRFWHRjeWNsZXMuVmlldyBMYXllci5zYW1wbGVzADI1Nlh8UgYAAAAldEVYdGN5Y2xlcy5WaWV3IExheWVyLnRvdGFsX3RpbWUAMDA6MDAuNzTqCjkZAAAAJnRFWHRjeWNsZXMuVmlldyBMYXllci5yZW5kZXJfdGltZQAwMDowMC4wOWJzJbgAAAAvdEVYdGN5Y2xlcy5WaWV3IExheWVyLnN5bmNocm9uaXphdGlvbl90aW1lADAwOjAwLjY0K1WWNwAAECtJREFUWAkBIBDf7wEBAQEAAAAAAP///wABAQEAAQEBAP///wD///8AAQEBAAAAAAD///8AAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAP///wACAgIA////AAAAAAAAAAAAAAAAAAEBAQD///8AAAAAAAAAAAAAAAAA////AAEBAQAAAAAA////AAEBAQEAAAAAAAAAAAAAAAAA////AAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAP///wAAAAAAAAAAAAAAAAABAQEA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEA/wD/ALj+/gECBQYAwv7+AQQGBwDD/v4B/wABAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAAAAAD///8AAAAAAAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAEBAQEAAAAAAAAAAAAAAQEA+P39CPIAAB8BAAAGAAAAAAAAAAABAAAA/wAAAf8AAAACAAD+/QAAAgQAAP/9AAAAAQAA//8AAAEBAAAAAAAA/wMAAAH+AAABAgAA/wAAAAAAAAAAAwAA//sAAPgMAADhCAIC+wAAAAABAQEA////AAEBAQEAAAAAAAEBAQD9/f0B7QAAYAQAAIT+AAAGAQAAAQAAAAAAAAD//wAAAQAAAAAAAAAB/wAA/wIAAAD/AAAAAAAAAQAAAP4AAAACAAAA/wAAAAAAAAABAQAAAP8AAP8BAAAA/wAA/wMAAPjyAAB+3QAAoEIDA/////8AAAAAAAQAAAAAAAAAAP///wAAAAAA9AAA9hEAAA3/AAANAQAAAP8AAAABAAAAAQAAAAAAAAAAAAAAAAAAAP8AAAACAAAA/wAAAAAAAAD/AAAA/wAAAAAAAAD/AAAAAgAAAAAAAAD+AAAA/wAAAAYAAPf/AAD4HQAAAP7+/wABAQAAAAAAAAIBAQEAAAAAAAAAAAACBAP/CAAAufcAALcBAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AAAAAAAAAP8AAAAAAAAAAQAAAAAAAAAAAAAAAAAAAP8AAAD/AAAAAwAA/fgAALQFAAC3JAMC/wEBAAAAAAAAAAAAAAL///8AAAAAAAAAAAAA/v8AFwAA8QAAAIf9AADcAAAAAP8AAAD/AAAA/wAAAAAAAAD/AAAAAAAAAAEAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAAAACAAAAAAAAAAAAAAADAAAAAQAA4voAAIUaBQLwAP8AAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAQEB/xcAANH8AACLAAAA9wIAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAP8AAAAAAAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAEAAAADAAD4+AAAiBUAANQA/QAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAQEBAAICAv8LAACn/gAAqgAAAP4AAAAAAAAAAP8AAAAAAAAAAQAAAAAAAAABAAAAAQAAAAEAAAAAAAAAAAAAAP8AAAABAAAAAQAAAAIAAP36AACoAwAApwYCAv0AAAAA////AAEBAQAAAAAAAAAAAAIBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAADvAAD1/wAAjf4AANwBAAD+AAAAAAEAAAAAAAAA/wAAAAAAAAD/AAAA/wAAAP8AAAAAAAAAAAAAAAEAAAD/AAAAAQAAAP8AAN3+AACMFwcD8wAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAL///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAhAwP/EwAA1f4AAIUAAAD0AgAAAP8AAAAAAAAAAAAAAAEAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAA9PoAAIX+AADY//v/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgIC/gAAAK79AACvAAAA/gEAAAAAAAAA/wAAAP8AAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAADAAAA+QAArQYAAK0aAwP9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQD///8AAAAAABwMC/T9AACJ/gAA1AEAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAAAAAAAAAAA/wAAAAEAAAD8AADXAAAAhRICAvX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAPr29wAJAADa+gAAiQEAAPIAAAAAAAAAAP8AAAAAAAAA/wAAAAAAAAAAAAAAAAAAAAIAAPL+AACFBAAA3gAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAD///8AAAAAAAIBAQEAAAAAAAAAAAAAAAAAAAAAAP///wAAAAAA/v7+AAAAAAAPAgL9BgAAr/sAAKkBAAD9AQAAAAAAAAD/AAAA/wAAAAEAAAAAAAAAAwAA/fgAAKkHAACtEgIC/QAAAAAAAAAAAQEBAAAAAAACAgIAAAAAAAAAAAABAQEAAAAAAAEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwYEAOr4+iD+AACuBAAAMP4AAAH/AAAAAgAAAAAAAAAAAAAA+wAA0AMAAFQUAgLdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/vv9ABEAAOIAAACH/wAA8QEAAAABAAAA/QAAAP8AAAACAADxAAAAigwAAN4AAAAA////AAAAAAAAAAAAAQEBAAAAAAAAAAAAAAAAAAEBAQAAAAAAAAAAAAL///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAICAv4OAAC0/QAApAEAAP0AAAAAAQAAAAMAAP31AACkEwAArwgCAv8AAAAAAQEBAAEBAQAAAAAA////AAAAAAAAAAAAAQEBAP///wAAAAAAAQEBAAABAQEAAQEBAAEBAQABAQEAAQEBAAEBAQAAAAAAAQEBAAEBAQABAQEAAQEBAAEBAQDg//8B7///JO3//87v////8v///+r//83x//8fAQEBAAEBAQABAQEAAQEBAAICAgABAQEAAQEBAAEBAQABAQEAAQEBAAEBAQABAQEAAQEBAAABAQEAAQEBAAEBAQABAQEAAQEBAAEBAQABAQEAAQEBAAEBAQABAQEAAQEBAAEBAQABAQEA////Auv//0rt///e7///3ev//0vv//8CAQEBAAEBAQABAQEAAQEBAAEBAQABAQEAAAAAAAEBAQABAQEAAQEBAAEBAQABAQEAAQEBAAEBAQEAAAAAAAEBAQD///8AAAAAAAAAAAAAAAAA////AAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAPn+/gT0AAAn/AAAABUAANYCAgL/AAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAP8AAADV/f0BLQYF//78/QAAAAAAAAAAAAAAAAD///8AAQEBAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAQEBAAEBAQEAAAAAAAAAAAAAAAAA////AAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAQEBAAIAAAAAAQEBAAAAAAAAAAAAAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQAAAAAA////AAEBAQABAQEAAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAEBAQD///8AAAAAAAAAAAAAAAAAAAAAAAEBAQEAAAAAAAAAAAAAAAAA////AAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAP///wAAAAAAAAAAAAAAAAAAAAAAAQEBAAMBAQEAAAAAAAAAAAAAAAAAAQEBAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMBAQEAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAEAAAAAAAAAAAEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEA////AP///wACAgIA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAICAgAAAAAA////AAAAAAAAAAAAAAAAAE2vxmTH5SrmAAAANmVYSWZNTQAqAAAAGAAAAEgAAAABAAAASAAAAAEAAgEaAAUAAAABAAAACAEbAAUAAAABAAAAEAAAAACQeO+8AAAAAElFTkSuQmCC"));

		return mempath;
	}

	/// <summary>Get base directory of config files.</summary>
	/// <returns>A string representing the path of the base directory.</returns>
	/// <remarks>
	/// Values on different platforms:
	///     Windows: <user>\AppData\Roaming
	///     Linux/macOS: ${XDG_CONFIG_HOME:-$HOME/.config}
	/// </remarks>
	/// <seealso href="https://jimrich.sk/environment-specialfolder-on-windows-linux-and-os-x/" /> 
	private static string GetConfigBaseDir() => Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);

	/// <summary>Get base directory of data files.</summary>
	/// <returns>A string representing the path of the base directory.</returns>
	/// <remarks>
	/// Values on different platforms:
	///     Windows: <user>\AppData\Local
	///     Linux/macOS: ${XDG_DATA_HOME:-$HOME/.local/share} 
	/// </remarks>
	/// <seealso href="https://jimrich.sk/environment-specialfolder-on-windows-linux-and-os-x/" />
	private static string GetDataBaseDir() => Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);

	/// <summary>Get base directory of cache files.</summary>
	/// <returns>A string representing the path of the base directory.</returns>
	/// <remarks>
	/// Values on different platforms:
	///     Windows: %TEMP% or %TMP% or <user>\AppData\Local\Temp
	///     Linux/macOS: ${XDG_CACHE_HOME:-$HOME/.cache}
	/// </remarks>
	/// <seealso href="https://jimrich.sk/environment-specialfolder-on-windows-linux-and-os-x/" />
	/// <seealso href="https://en.wikipedia.org/wiki/Environment_variable#Default_values" />
	/// <seealso href="https://specifications.freedesktop.org/basedir-spec/latest/#variables" />  
	private static string GetCacheBaseDir() =>
#if COMPILED_WINDOWS
		Environment.GetEnvironmentVariable("TEMP")
	?? Environment.GetEnvironmentVariable("TMP")
	?? System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Temp");
#else
		Environment.GetEnvironmentVariable("XDG_CACHE_HOME")
	?? System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".cache");
#endif

	/// <summary>Get base directory of state files.</summary>
	/// <returns>A string representing the path of the base directory.</returns>
	/// <remarks>
	/// Values on different platforms:
	///     Windows: Same to <see cref="GetCacheBaseDir" />
	///     Linux/macOS: ${XDG_STATE_HOME:-$HOME/.local/state}
	/// As Windows does not have similar concept, we use cache directory here instead.
	/// </remarks>
	/// <seealso href="https://jimrich.sk/environment-specialfolder-on-windows-linux-and-os-x/" />
	/// <seealso href="https://specifications.freedesktop.org/basedir-spec/latest/#variables" />
	private static string GetStateBaseDir() =>
#if COMPILED_WINDOWS
		GetCacheBaseDir();
#else
		Environment.GetEnvironmentVariable("XDG_STATE_HOME")
	?? System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".local", "state");
#endif

	private DiskSearchPath AddBaseGameSearchPaths() {
		return AddSearchPath<DiskSearchPath>("game", AppContext.BaseDirectory);
	}

	private void AddConfigSearchPaths(DiskSearchPath gameDiskSearchPath, ReadOnlySpan<char> gameName) {
		// This acts as the primary config search path (mounted at the head of the filesystem),
		AddSearchPath("cfg", DiskSearchPath.Combine(new DiskSearchPath(GetConfigBaseDir()), gameName));

		// XDG base directory support
		// XDG_CONFIG_DIRS sets a set of extra base directories which each one needs to be searched like ${XDG_CONFIG_HOME:-$HOME/.config}.
		// As DiskSearchPath will try creating that directory, we only add it when actually exists.
#if !COMPILED_WINDOWS
		string xdgConfigDirs = Environment.GetEnvironmentVariable("XDG_CONFIG_DIRS") ?? "/etc/xdg";
		foreach (string path in xdgConfigDirs.Split(':'))
			if (Directory.Exists(System.IO.Path.Combine(path, gameName.ToString())))
				AddSearchPath("cfg", DiskSearchPath.Combine(new DiskSearchPath(path), gameName));
#endif
		// For older Nucleus application installs; if game/cfg exists, we'll mount it at the tail.
		// New cfg writes will happen to the new folders at the head
		var cfgLegacy = DiskSearchPath.Combine(gameDiskSearchPath, "cfg");
		if (cfgLegacy.Exists())
			AddSearchPath("cfg", cfgLegacy);
	}

	private void AddAppDataSearchPaths(ReadOnlySpan<char> gameName) {
		// This is where we store persist data, game will not work correctly without them.
		AddSearchPath("appdata", DiskSearchPath.Combine(new DiskSearchPath(GetDataBaseDir()), gameName));
		// XDG base directory support
		// XDG_DATA_DIRS sets a set of extra base directories which each one needs to be searched like ${XDG_DATA_HOME:-$HOME/.local/share}.
		// As DiskSearchPath will try creating that directory, we only add it when actually exists.
#if !COMPILED_WINDOWS
		string xdgDataDirs = Environment.GetEnvironmentVariable("XDG_DATA_DIRS") ?? "/usr/local/share:/usr/share";
		foreach (string path in xdgDataDirs.Split(':'))
			if (Directory.Exists(System.IO.Path.Combine(path, gameName.ToString())))
				AddSearchPath("appdata", DiskSearchPath.Combine(new DiskSearchPath(path), gameName));
#endif
	}

	private void AddAppCacheSearchPaths(ReadOnlySpan<char> gameName) {
		// This is where we store cache data, game can generate them again if needed.
		AddSearchPath("appcache", DiskSearchPath.Combine(new DiskSearchPath(GetCacheBaseDir()), gameName));
	}

	private void AddAppStateSearchPaths(ReadOnlySpan<char> gameName) {
		// This is where we store persistent data that isn't important `appdata`, like history, logs, etc.
		AddSearchPath("appstate", DiskSearchPath.Combine(new DiskSearchPath(GetStateBaseDir()), gameName));
	}

	private void AddUserAssets(DiskSearchPath gameDiskSearchPath) {
		var assets = AddSearchPath("assets", DiskSearchPath.Combine(gameDiskSearchPath, "assets"));
		{
			AddSearchPath("audio", DiskSearchPath.Combine(assets, "audio"));
			AddSearchPath("fonts", DiskSearchPath.Combine(assets, "fonts"));
			AddSearchPath("images", MemBackedImages());
			AddSearchPath("images", DiskSearchPath.Combine(assets, "images"));
			AddSearchPath("models", DiskSearchPath.Combine(assets, "models"));
			AddSearchPath("shaders", DiskSearchPath.Combine(assets, "shaders"));
		}
	}

	public void Initialize(ReadOnlySpan<char> gameName) {
		if (initialized)
			return;

		var gameDiskSearchPath = AddBaseGameSearchPaths();
		AddConfigSearchPaths(gameDiskSearchPath, gameName);
		AddAppDataSearchPaths(gameName);
		AddAppCacheSearchPaths(gameName);
		AddAppStateSearchPaths(gameName);
		AddUserAssets(gameDiskSearchPath);

		initialized = true;
	}

	/// <summary>
	/// Gets, or creates, a <see cref="SearchPathID"/>
	/// </summary>
	/// <param name="pathID"></param>
	/// <returns></returns>
	public SearchPathID GetSearchPathID(ReadOnlySpan<char> pathID) {
		if (Path.TryGetValue(pathID.Hash(), out var pathIDObj))
			return pathIDObj;

		pathIDObj = new();
		Path[pathID.Hash()] = pathIDObj;

		return pathIDObj;
	}

	IEnumerable<SearchPath> IFileSystem.GetSearchPathID(ReadOnlySpan<char> pathID) => GetSearchPathID(pathID);

	public T AddSearchPath<T>(ReadOnlySpan<char> pathID, T searchPath, SearchPathAdd add = SearchPathAdd.ToTail) where T : SearchPath {
		var pathIDObj = GetSearchPathID(pathID);
		switch (add) {
			case SearchPathAdd.ToHead:
				pathIDObj.Insert(0, searchPath);
				break;
			case SearchPathAdd.ToTail:
				pathIDObj.Add(searchPath);
				break;
		}
		return searchPath;
	}

	public T AddSearchPath<T>(ReadOnlySpan<char> pathID, ReadOnlySpan<char> path, SearchPathAdd add = SearchPathAdd.ToTail) where T : SearchPath {
		T ret;
		switch (typeof(T).Name) {
			case nameof(DiskSearchPath):
				ret = (T)(object)new DiskSearchPath(path);
				break;
			default: throw new NotImplementedException($"Unknown FileSystem type '{typeof(T).Name}'. Please implement it in Nucleus.Core.FileSystem.");
		}

		AddSearchPath(pathID, ret, add);
		return ret;
	}


	readonly struct TemporarySearchPathInfo
	{
		public readonly SearchPath searchPath;
		public readonly string pathID;

		public TemporarySearchPathInfo(SearchPath searchPath, string pathID) {
			this.searchPath = searchPath;
			this.pathID = pathID;
		}
	}
	readonly List<TemporarySearchPathInfo> temporarySearchPaths = [];

	/// <summary>
	/// Adds a search path that is destroyed when the level is deinitialized.
	/// </summary>
	/// <typeparam name="T"></typeparam>
	/// <param name="pathID"></param>
	/// <param name="path"></param>
	/// <param name="add"></param>
	/// <returns></returns>
	public T AddTemporarySearchPath<T>(ReadOnlySpan<char> pathID, ReadOnlySpan<char> path, SearchPathAdd add = SearchPathAdd.ToTail) where T : SearchPath {
		var pathObj = AddSearchPath<T>(pathID, path, add);
		temporarySearchPaths.Add(new(pathObj, new string(pathID)));
		return pathObj;
	}

	public T AddTemporarySearchPath<T>(ReadOnlySpan<char> pathID, T path, SearchPathAdd add = SearchPathAdd.ToTail) where T : SearchPath {
		var pathObj = AddSearchPath(pathID, path, add);
		temporarySearchPaths.Add(new(pathObj, new string(pathID)));
		return pathObj;
	}

	public void RemoveTemporarySearchPaths() {
		foreach (var temp in temporarySearchPaths)
			RemoveSearchPath(temp.pathID, temp.searchPath);
	}

	public bool RemoveSearchPath(ReadOnlySpan<char> pathID, SearchPath path) {
		if (!Path.TryGetValue(pathID.Hash(), out var pathIDObj)) return false;
		return pathIDObj.Remove(path);
	}

	public bool RemoveSearchPath(ReadOnlySpan<char> pathID) {
		if (!Path.TryGetValue(pathID.Hash(), out var pathIDObj)) return false;
		return pathIDObj.RemoveAll(x => true) > 0;
	}

	public SearchPath? FindSearchPath(ReadOnlySpan<char> pathID, ReadOnlySpan<char> path) {
		foreach (var pathIDObj in GetSearchPathID(pathID))
			if (pathIDObj.Exists(path))
				return pathIDObj;

		return null;
	}

	// Fixes annoying complaints about ref types crossing yield boundaries
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	IEnumerable<string> findFiles(string pathID, string searchPattern, SearchOption searchOptions = SearchOption.TopDirectoryOnly) {
		foreach (var pathIDObj in GetSearchPathID(pathID))
			foreach (var file in pathIDObj.FindFiles("", searchPattern, searchOptions))
				yield return file;
	}
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	IEnumerable<string> findDirectories(string pathID, string searchPattern, SearchOption searchOptions = SearchOption.TopDirectoryOnly) {
		foreach (var pathIDObj in GetSearchPathID(pathID))
			foreach (var file in pathIDObj.FindDirectories("", searchPattern, searchOptions))
				yield return file;
	}
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	IEnumerable<string> findFiles(string pathID, string path, string searchPattern, SearchOption searchOptions = SearchOption.TopDirectoryOnly) {
		foreach (var pathIDObj in GetSearchPathID(pathID))
			foreach (var file in pathIDObj.FindFiles(path, searchPattern, searchOptions))
				yield return file;
	}
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	IEnumerable<string> findDirectories(string pathID, string path, string searchPattern, SearchOption searchOptions = SearchOption.TopDirectoryOnly) {
		foreach (var pathIDObj in GetSearchPathID(pathID))
			foreach (var file in pathIDObj.FindDirectories(path, searchPattern, searchOptions))
				yield return file;
	}

	//=========================================================================================================================================================//
	//=========================================================================================================================================================//
	//=========================================================================================================================================================//
	//=========================================================================================================================================================//
	//=========================================================================================================================================================//

	public IEnumerable<string> FindFiles(ReadOnlySpan<char> pathID, ReadOnlySpan<char> searchPattern, SearchOption searchOptions = SearchOption.TopDirectoryOnly) {
		return findFiles(new(pathID), new(searchPattern), searchOptions);
	}

	public IEnumerable<string> FindDirectories(ReadOnlySpan<char> pathID, ReadOnlySpan<char> searchPattern, SearchOption searchOptions = SearchOption.TopDirectoryOnly) {
		return findDirectories(new(pathID), new(searchPattern), searchOptions);
	}

	public IEnumerable<string> FindFiles(ReadOnlySpan<char> pathID, ReadOnlySpan<char> path, ReadOnlySpan<char> searchPattern, SearchOption searchOptions = SearchOption.TopDirectoryOnly) {
		return findFiles(new(pathID), new(searchPattern), new(searchPattern), searchOptions);
	}

	public IEnumerable<string> FindDirectories(ReadOnlySpan<char> pathID, ReadOnlySpan<char> path, ReadOnlySpan<char> searchPattern, SearchOption searchOptions = SearchOption.TopDirectoryOnly) {
		return findDirectories(new(pathID), new(searchPattern), new(searchPattern), searchOptions);
	}

	public bool CanOpen(ReadOnlySpan<char> pathID, ReadOnlySpan<char> path, FileAccess access = FileAccess.ReadWrite, FileMode mode = FileMode.OpenOrCreate) {
		foreach (var pathObj in GetSearchPathID(pathID)) {
			if (pathObj.CheckFile(path, access, mode))
				return true;
		}

		return false;
	}

	public Stream? Open(ReadOnlySpan<char> pathID, ReadOnlySpan<char> path, FileAccess access = FileAccess.ReadWrite, FileMode mode = FileMode.OpenOrCreate) {
		foreach (var pathObj in GetSearchPathID(pathID)) {
			if (pathObj.CheckFile(path, access, mode)) {
				var stream = pathObj.Open(path, access, mode);
				if (stream != null) return stream;
			}
		}

		return null;
	}

	public bool Exists(string pathID, string path) {
		foreach (var pathObj in GetSearchPathID(pathID))
			if (pathObj.Exists(path))
				return true;

		return false;
	}

	public string? ReadAllText(string pathID, string path) {
		foreach (var pathObj in GetSearchPathID(pathID)) {
			var text = pathObj.ReadText(path);
			if (text != null) return text;
		}

		return null;
	}

	public byte[]? ReadAllBytes(string pathID, string path) {
		foreach (var pathObj in GetSearchPathID(pathID)) {
			var bytes = pathObj.ReadBytes(path);
			if (bytes != null) return bytes;
		}

		return null;
	}

	public bool ReadAllText(string pathID, string path, [NotNullWhen(true)] out string? text) {
		text = ReadAllText(pathID, path);
		return text != null;
	}

	public bool ReadAllBytes(string pathID, string path, [NotNullWhen(true)] out byte[]? bytes) {
		bytes = ReadAllBytes(pathID, path);
		return bytes != null;
	}

	public bool WriteAllText(ReadOnlySpan<char> pathID, ReadOnlySpan<char> path, ReadOnlySpan<char> text, Encoding encoding) {
		foreach (var pathObj in GetSearchPathID(pathID)) {
			var succeeded = pathObj.WriteText(path, text, encoding);
			if (succeeded) return true;
		}

		return false;
	}

	public bool WriteAllText(ReadOnlySpan<char> pathID, ReadOnlySpan<char> path, ReadOnlySpan<char> text) {
		foreach (var pathObj in GetSearchPathID(pathID)) {
			var succeeded = pathObj.WriteText(path, text);
			if (succeeded) return true;
		}

		return false;
	}

	public bool WriteAllBytes(ReadOnlySpan<char> pathID, ReadOnlySpan<char> path, byte[] data) {
		foreach (var pathObj in GetSearchPathID(pathID)) {
			var succeeded = pathObj.WriteBytes(path, data);
			if (succeeded) return true;
		}

		return false;
	}
}
