<Project>
	<PropertyGroup>
		<IsWindows>$([MSBuild]::IsOSPlatform('Windows'))</IsWindows>
		<IsOSX>$([MSBuild]::IsOSPlatform('OSX'))</IsOSX>
		<IsLinux>$([MSBuild]::IsOSPlatform('Linux'))</IsLinux>
	</PropertyGroup>

	<Target Name="NucleusPreBuild" BeforeTargets="PreBuildEvent">
		<ItemGroup>
			<UniversalAssets_Nucleus Include="$(MSBuildThisFileDirectory)\BuildAssets\universal\**\*" />
			<PlatformAssets_Nucleus Condition="'$(IsWindows)' == 'true'" Include="$(MSBuildThisFileDirectory)\BuildAssets\winnt\**\*" />
			<PlatformAssets_Nucleus Condition="'$(IsOSX)' == 'true'" Include="$(MSBuildThisFileDirectory)\BuildAssets\intel_osx\**\*" />
			<PlatformAssets_Nucleus Condition="'$(IsLinux)' == 'true'" Include="$(MSBuildThisFileDirectory)\BuildAssets\linux\**\*" />
			<OSXNativeLibs Condition="'$(IsOSX)' == 'true'" Include="$(MSBuildThisFileDirectory)\BuildAssets\intel_osx\*.dylib" />
		</ItemGroup>

		<Copy SourceFiles="@(UniversalAssets_Nucleus)" DestinationFolder="$(OutDir)%(RecursiveDir)" SkipUnchangedFiles="true" />
		<Copy SourceFiles="@(PlatformAssets_Nucleus)" DestinationFolder="$(OutDir)%(RecursiveDir)" SkipUnchangedFiles="true" />
		<Copy Condition="'$(IsOSX)' == 'true'" SourceFiles="@(OSXNativeLibs)" DestinationFolder="$(OutDir)runtimes\osx-arm64\native\" SkipUnchangedFiles="true" />
	</Target>

	<Target Name="NucleusCopyPublishAssets" AfterTargets="Publish">
		<ItemGroup>
			<UniversalAssets_Nucleus Include="$(MSBuildThisFileDirectory)\BuildAssets\universal\**\*" />
			<PlatformAssets_Nucleus Condition="'$(IsWindows)' == 'true'" Include="$(MSBuildThisFileDirectory)\BuildAssets\winnt\**\*" />
			<PlatformAssets_Nucleus Condition="'$(IsOSX)' == 'true'" Include="$(MSBuildThisFileDirectory)\BuildAssets\intel_osx\**\*" />
			<PlatformAssets_Nucleus Condition="'$(IsLinux)' == 'true'" Include="$(MSBuildThisFileDirectory)\BuildAssets\linux\**\*" />
			<OSXNativeLibs Condition="'$(IsOSX)' == 'true'" Include="$(MSBuildThisFileDirectory)\BuildAssets\intel_osx\*.dylib" />
		</ItemGroup>

		<Copy SourceFiles="@(UniversalAssets_Nucleus)" DestinationFolder="$(PublishDir)%(RecursiveDir)" SkipUnchangedFiles="true" />
		<Copy SourceFiles="@(PlatformAssets_Nucleus)" DestinationFolder="$(PublishDir)%(RecursiveDir)" SkipUnchangedFiles="true" />
		<Copy Condition="'$(IsOSX)' == 'true'" SourceFiles="@(OSXNativeLibs)" DestinationFolder="$(PublishDir)runtimes\osx-arm64\native\" SkipUnchangedFiles="true" />
	</Target>
</Project>